const authRoutes = require("../api/routes/auth.routes")
const turmaRoutes = require("../api/routes/turma.routes")
const serieRoutes = require("../api/routes/serie.routes")
const alunoRoutes = require("../api/routes/aluno.routes")
const professorRoutes = require("../api/routes/professor.routes")
const pastaRoutes = require("../api/routes/pasta.routes")
const arquivoRoutes = require("../api/routes/arquivo.routes")
const materiaRoutes = require("../api/routes/materia.routes")
const avaliacaoRoutes = require("../api/routes/avaliacao.routes")
const notaRoutes = require("../api/routes/nota.routes")
const avisosRoutes = require("../api/routes/aviso.routes")

module.exports = (app) => {
  app.use("/api/auth", authRoutes)
  app.use("/api/turmas", turmaRoutes)
  app.use("/api/series", serieRoutes)
  app.use("/api/alunos", alunoRoutes)
  app.use("/api/professores", professorRoutes)
  app.use("/api/pastas", pastaRoutes)
  app.use("/api/arquivos", arquivoRoutes)
  app.use("/api/materias", materiaRoutes)
  app.use("/api/avaliacoes", avaliacaoRoutes)
  app.use("/api/notas", notaRoutes)
  app.use("/api/avisos", avisosRoutes)
}
